version: "3"
services:
    # web:
    #     image: accountgo/accountgoweb
    #     build: 
    #         dockerfile: ./src/AccountGoWeb/Dockerfile
    #         context: .
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - api
    #     environment:
    #         - ASPNETCORE_ENVIRONMENT=Development
    #         - ASPNETCORE_URLS=https://+;http://+
    #         - ASPNETCORE_HTTPS_PORT=44300
    api:
        image: accountgo/accountgoapi
        build:
            dockerfile: ./src/Api/Dockerfile
            context: .
        ports:
            - "8001:8001"
            - "44301:44301"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+
            - ASPNETCORE_HTTPS_PORT=44301
        depends_on:
            - db
    db:
        image: microsoft/mssql-server-linux
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Str0ngPassword"
            ACCEPT_EULA: "Y"